name: Bruno API Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bruno-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Verify Bruno installation
        run: bru --version

      - name: Prepare report directory
        run: mkdir -p reports

      - name: Run Bruno collection
        working-directory: bruno
        run : |
            bru run collections/** --env-var baseUrl=https://qa-practice-vrc.vercel.app
            --reporter-html ../../reports/github-actions-report.html

      - name: Upload Bruno report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: bruno-report
          path: reports
          if-no-files-found: warn
